// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeFLF57BxT8CIOj10UaN0q2cTT7Mry4no',
    appId: '1:216558571275:web:e554c49ec7bf3f659d9c0e',
    messagingSenderId: '216558571275',
    projectId: 'rizziconsultingrms',
    authDomain: 'rizziconsultingrms.firebaseapp.com',
    storageBucket: 'rizziconsultingrms.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLAwpRQA5nlon5qOa_I1W2iv__T1K3oS8',
    appId: '1:216558571275:android:747624b7cd9bc9469d9c0e',
    messagingSenderId: '216558571275',
    projectId: 'rizziconsultingrms',
    storageBucket: 'rizziconsultingrms.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArIiv7i84fzLSzLvfsMEqo0p0rkXvGoNk',
    appId: '1:216558571275:ios:ba20bcf73d884de69d9c0e',
    messagingSenderId: '216558571275',
    projectId: 'rizziconsultingrms',
    storageBucket: 'rizziconsultingrms.appspot.com',
    iosClientId: '216558571275-klr13e8oia2p31fhv4rmnp8kdqgsvatu.apps.googleusercontent.com',
    iosBundleId: 'com.rizziconsultong.rms',
  );
}
